[options]
addons_path = C:\Program Files\Odoo 15.0.20250101\server\odoo\addons,C:\Program Files\Odoo 15.0.20250101\server\addons,C:\odoo\custom_addons\SICAWeb-main
admin_passwd = 9655@Muthu
#~ admin_passwd = $pbkdf2-sha512$25000$5zxnDEGolTJmLOXcu9faGw$II/S3/OHeL1BEg/vscVrZQ8fKiIMi4/xMzW52aqh3gKMoM0X958UItcRyKTDon6LiJbRD1bpWKPI3uUOebW.5w
db_host =localhost
db_password = odoo
db_port = 5433
db_user = odoo
http_port = 8059
workers = 0
db_name = sicadop_02
limit_time_cpu = 3600
limit_time_real = 3600
debug =656565666424235
limit_memory_hard = 3221225472
limit_memory_soft = 3221225472
#logfile =/var/log/odoo/kci1.log
#pg_path = /usr/lib/postgresql/14/bin
#wkhtmltopdf = /path/to/wkhtmltopdf
ODOO_URL      = "http://localhost:8059"
ODOO_DB       = "sicadop_02"
ODOO_USER     = "admin"        # your Odoo username
ODOO_PASSWORD = "admin"        # your Odoo password
